// const arr = [
//     [
//       "Rødseth",
//       "Female",
//       "3401 Sørkedalsveien Øystese",
//       "Opplan Norway",
//       "celine.rodseth@example.com",
//       "popcorn",
//       "https://randomuser.me/api/portraits/women/10.jpg"
//     ],
//     [
//       "Deez nutz",
//       "Male",
//       "6199 London Road Salisbury",
//       "Somerset United Kingdom",
//       "julian.dunn@example.com",
//       "terry1",
//       "https://randomuser.me/api/portraits/men/34.jpg"
//     ],
//     [
//       "Brosch",
//       "Male",
//       "5297 Am Sportplatz Stromberg",
//       "Brandenburg Germany",
//       "bnymyn.sdr@example.com",
//       "alibaba",
//       "https://randomuser.me/api/portraits/men/86.jpg"
//     ],
//     [
//       "Ginnish",
//       "Female",
//       "5469 Grand Marais Ave Princeton",
//       "Saskatchewan Canada",
//       "arthur.ginnish@example.com",
//       "access14",
//       "https://randomuser.me/api/portraits/men/67.jpg"
//     ],
//     [
//       "Nalbantoğlu",
//       "Female",
//       "8313 Vatan Cd Batman",
//       "Çanakkale Turkey",
//       "begum.nalbantoglu@example.com",
//       "3434",
//       "https://randomuser.me/api/portraits/men/72.jpg"
//     ],
//     [
//       "Diaz",
//       "Female",
//       "4820 Calle de Arturo Soria Jerez de la Frontera",
//       "Castilla y León Spain",
//       "remedios.diaz@example.com",
//       "bigbig",
//       "https://randomuser.me/api/portraits/men/38.jpg"
//     ],
//     [
//       "Babić",
//       "Female",
//       "4924 Milana Ristanovića Rekovac",
//       "Kolubara Serbia",
//       "hadrien.leclerc@example.com",
//       "westham",
//       "https://randomuser.me/api/portraits/men/93.jpg"
//     ],
//     [
//       "Blažić",
//       "Male",
//       "763 Mladena Nedeljkovića Novi Bečej",
//       "Nišava Serbia",
//       "hadrien.leclerc@example.com",
//       "westham",
//       "https://randomuser.me/api/portraits/women/60.jpg"
//     ],
//     [
//       "Nissen",
//       "Male",
//       "117 Munkerudkleiva Stikkaåsen",
//       "Vest-Agder Norway",
//       "julia.nissen@example.com",
//       "KYOZ01ze",
//       "https://randomuser.me/api/portraits/women/34.jpg"
//     ],
//     [
//       "Hansen",
//       "Male",
//       "9150 Dane St Provo",
//       "Arizona United States",
//       "celine.rodseth@example.com",
//       "sdfjka",
//       "https://randomuser.me/api/portraits/men/10.jpg"
//     ],
//   ];

const arr=[
    [
        "female",
        "Celine",
        "Rødseth",
        "Sørkedalsveien",
        "Øystese",
        "Oppland",
        "Norway",
        "celine.rodseth@example.com",
        "yellowkoala710",
        "popcorn",
        "FN",
        "https://randomuser.me/api/portraits/women/10.jpg",
        "https://randomuser.me/api/portraits/med/women/10.jpg",
        "https://randomuser.me/api/portraits/thumb/women/10.jpg"
    ],
    [
        "male",
        "Julian",
        "Dunn",
        "London Road",
        "Salisbury",
        "Somerset",
        "United Kingdom",
        "julian.dunn@example.com",
        "yellowleopard451",
        "terry1",
        "NINO",
        "https://randomuser.me/api/portraits/men/34.jpg",
        "https://randomuser.me/api/portraits/med/men/34.jpg",
        "https://randomuser.me/api/portraits/thumb/men/34.jpg"
    ],
    [
        "male",
        "بنیامین",
        "صدر",
        "وحدت اسلامی",
        "آبادان",
        "کرمانشاه",
        "Iran",
        "bnymyn.sdr@example.com",
        "goldendog604",
        "alibaba",
        "",
        "https://randomuser.me/api/portraits/men/86.jpg",
        "https://randomuser.me/api/portraits/med/men/86.jpg",
        "https://randomuser.me/api/portraits/thumb/men/86.jpg"
    ],
    [
        "male",
        "Johan",
        "Brosch",
        "Am Sportplatz",
        "Stromberg",
        "Brandenburg",
        "Germany",
        "johan.brosch@example.com",
        "tinypanda968",
        "secret1",
        "SVNR",
        "https://randomuser.me/api/portraits/men/67.jpg",
        "https://randomuser.me/api/portraits/med/men/67.jpg",
        "https://randomuser.me/api/portraits/thumb/men/67.jpg"
    ],
    [
        "male",
        "Arthur",
        "Ginnish",
        "Grand Marais Ave",
        "Princeton",
        "Saskatchewan",
        "Canada",
        "arthur.ginnish@example.com",
        "sadfish773",
        "access14",
        "SIN",
        "https://randomuser.me/api/portraits/men/72.jpg",
        "https://randomuser.me/api/portraits/med/men/72.jpg",
        "https://randomuser.me/api/portraits/thumb/men/72.jpg"
    ],
    [
        "male",
        "Ali",
        "Keseroğlu",
        "Atatürk Sk",
        "Bingöl",
        "Bitlis",
        "Turkey",
        "ali.keseroglu@example.com",
        "redbutterfly421",
        "luckydog",
        "",
        "https://randomuser.me/api/portraits/men/38.jpg",
        "https://randomuser.me/api/portraits/med/men/38.jpg",
        "https://randomuser.me/api/portraits/thumb/men/38.jpg"
    ],
    [
        "male",
        "Aloke",
        "Banerjee",
        "MG Rd Bangalore",
        "Panchkula",
        "Sikkim",
        "India",
        "aloke.banerjee@example.com",
        "angrylion183",
        "nomore",
        "UIDAI",
        "https://randomuser.me/api/portraits/men/93.jpg",
        "https://randomuser.me/api/portraits/med/men/93.jpg",
        "https://randomuser.me/api/portraits/thumb/men/93.jpg"
    ],
    [
        "female",
        "Begüm",
        "Nalbantoğlu",
        "Vatan Cd",
        "Batman",
        "Çanakkale",
        "Turkey",
        "begum.nalbantoglu@example.com",
        "orangebear321",
        "3434",
        "",
        "https://randomuser.me/api/portraits/women/60.jpg",
        "https://randomuser.me/api/portraits/med/women/60.jpg",
        "https://randomuser.me/api/portraits/thumb/women/60.jpg"
    ],
    [
        "female",
        "Remedios",
        "Diaz",
        "Calle de Arturo Soria",
        "Jerez de la Frontera",
        "Castilla y León",
        "Spain",
        "remedios.diaz@example.com",
        "purplebird361",
        "bigbig",
        "DNI",
        "https://randomuser.me/api/portraits/women/34.jpg",
        "https://randomuser.me/api/portraits/med/women/34.jpg",
        "https://randomuser.me/api/portraits/thumb/women/34.jpg"
    ],
    [
        "male",
        "Rico",
        "Lemm",
        "Schillerstraße",
        "Hallstadt",
        "Schleswig-Holstein",
        "Germany",
        "rico.lemm@example.com",
        "purplezebra740",
        "castor",
        "SVNR",
        "https://randomuser.me/api/portraits/men/10.jpg",
        "https://randomuser.me/api/portraits/med/men/10.jpg",
        "https://randomuser.me/api/portraits/thumb/men/10.jpg"
    ],
    [
        "female",
        "Jasna",
        "Babić",
        "Milana Ristanovića",
        "Rekovac",
        "Kolubara",
        "Serbia",
        "jasna.babic@example.com",
        "organicwolf686",
        "dogpound",
        "SID",
        "https://randomuser.me/api/portraits/women/91.jpg",
        "https://randomuser.me/api/portraits/med/women/91.jpg",
        "https://randomuser.me/api/portraits/thumb/women/91.jpg"
    ],
    [
        "male",
        "Hadrien",
        "Leclerc",
        "Avenue des Ternes",
        "Grenoble",
        "Saône-et-Loire",
        "France",
        "hadrien.leclerc@example.com",
        "blackfish745",
        "westham",
        "INSEE",
        "https://randomuser.me/api/portraits/men/90.jpg",
        "https://randomuser.me/api/portraits/med/men/90.jpg",
        "https://randomuser.me/api/portraits/thumb/men/90.jpg"
    ],
    [
        "female",
        "Ljiljana",
        "Blažić",
        "Mladena Nedeljkovića",
        "Novi Bečej",
        "Nišava",
        "Serbia",
        "ljiljana.blazic@example.com",
        "greenbird257",
        "emilia",
        "SID",
        "https://randomuser.me/api/portraits/women/64.jpg",
        "https://randomuser.me/api/portraits/med/women/64.jpg",
        "https://randomuser.me/api/portraits/thumb/women/64.jpg"
    ],
    [
        "female",
        "Julia",
        "Nissen",
        "Munkerudkleiva",
        "Stikkaåsen",
        "Vest-Agder",
        "Norway",
        "julia.nissen@example.com",
        "heavypanda408",
        "trinitro",
        "FN",
        "https://randomuser.me/api/portraits/women/39.jpg",
        "https://randomuser.me/api/portraits/med/women/39.jpg",
        "https://randomuser.me/api/portraits/thumb/women/39.jpg"
    ],
    [
        "female",
        "Terry",
        "Hansen",
        "Dane St",
        "Provo",
        "Arizona",
        "United States",
        "terry.hansen@example.com",
        "angrygoose773",
        "saturday",
        "SSN",
        "https://randomuser.me/api/portraits/women/61.jpg",
        "https://randomuser.me/api/portraits/med/women/61.jpg",
        "https://randomuser.me/api/portraits/thumb/women/61.jpg"
    ],
    [
        "female",
        "Thea",
        "Anderson",
        "Universal Drive",
        "Masterton",
        "Waikato",
        "New Zealand",
        "thea.anderson@example.com",
        "lazybear903",
        "20202020",
        "",
        "https://randomuser.me/api/portraits/women/35.jpg",
        "https://randomuser.me/api/portraits/med/women/35.jpg",
        "https://randomuser.me/api/portraits/thumb/women/35.jpg"
    ],
    [
        "male",
        "Adán",
        "Esquivel",
        "Diagonal Guanajuato",
        "Parícuaro",
        "Queretaro",
        "Mexico",
        "adan.esquivel@example.com",
        "beautifulgorilla399",
        "kendra",
        "NSS",
        "https://randomuser.me/api/portraits/men/28.jpg",
        "https://randomuser.me/api/portraits/med/men/28.jpg",
        "https://randomuser.me/api/portraits/thumb/men/28.jpg"
    ],
    [
        "female",
        "Jade",
        "Gagnon",
        "Duke St",
        "Red Rock",
        "Ontario",
        "Canada",
        "jade.gagnon@example.com",
        "reddog221",
        "boss",
        "SIN",
        "https://randomuser.me/api/portraits/women/92.jpg",
        "https://randomuser.me/api/portraits/med/women/92.jpg",
        "https://randomuser.me/api/portraits/thumb/women/92.jpg"
    ],
    [
        "female",
        "Skye",
        "Rog",
        "De Riethoek",
        "Vriezenveen",
        "Flevoland",
        "Netherlands",
        "skye.rog@example.com",
        "blackwolf299",
        "barney1",
        "BSN",
        "https://randomuser.me/api/portraits/women/43.jpg",
        "https://randomuser.me/api/portraits/med/women/43.jpg",
        "https://randomuser.me/api/portraits/thumb/women/43.jpg"
    ],
    [
        "female",
        "Celine",
        "Louis",
        "Place de L'Abbé-Franz-Stock",
        "Mettmenstetten",
        "Valais",
        "Switzerland",
        "celine.louis@example.com",
        "blackpeacock757",
        "case",
        "AVS",
        "https://randomuser.me/api/portraits/women/61.jpg",
        "https://randomuser.me/api/portraits/med/women/61.jpg",
        "https://randomuser.me/api/portraits/thumb/women/61.jpg"
    ],
    [
        "female",
        "Ada",
        "Buhalo",
        "Pestelya",
        "Soledar",
        "Rivnenska",
        "Ukraine",
        "ada.buhalo@example.com",
        "angrycat417",
        "paco",
        "",
        "https://randomuser.me/api/portraits/women/56.jpg",
        "https://randomuser.me/api/portraits/med/women/56.jpg",
        "https://randomuser.me/api/portraits/thumb/women/56.jpg"
    ],
    [
        "male",
        "Riley",
        "Turner",
        "Main Road",
        "Hereford",
        "Durham",
        "United Kingdom",
        "riley.turner@example.com",
        "ticklishleopard396",
        "triton",
        "NINO",
        "https://randomuser.me/api/portraits/men/36.jpg",
        "https://randomuser.me/api/portraits/med/men/36.jpg",
        "https://randomuser.me/api/portraits/thumb/men/36.jpg"
    ],
    [
        "female",
        "Noémie",
        "Sirko",
        "Pierre Ave",
        "New Glasgow",
        "Nova Scotia",
        "Canada",
        "noemie.sirko@example.com",
        "blueswan403",
        "striper",
        "SIN",
        "https://randomuser.me/api/portraits/women/89.jpg",
        "https://randomuser.me/api/portraits/med/women/89.jpg",
        "https://randomuser.me/api/portraits/thumb/women/89.jpg"
    ],
    [
        "female",
        "Emma",
        "Liu",
        "Brock Rd",
        "Lloydminster",
        "Ontario",
        "Canada",
        "emma.liu@example.com",
        "silverbird316",
        "carpedie",
        "SIN",
        "https://randomuser.me/api/portraits/women/30.jpg",
        "https://randomuser.me/api/portraits/med/women/30.jpg",
        "https://randomuser.me/api/portraits/thumb/women/30.jpg"
    ],
    [
        "female",
        "Emilie",
        "Gill",
        "Elgin St",
        "Victoria",
        "Ontario",
        "Canada",
        "emilie.gill@example.com",
        "whitesnake867",
        "billabon",
        "SIN",
        "https://randomuser.me/api/portraits/women/49.jpg",
        "https://randomuser.me/api/portraits/med/women/49.jpg",
        "https://randomuser.me/api/portraits/thumb/women/49.jpg"
    ],
    [
        "male",
        "Gabriel",
        "Dahl",
        "Breslauer Straße",
        "Rüsselsheim am Main",
        "Sachsen",
        "Germany",
        "gabriel.dahl@example.com",
        "goldenostrich604",
        "zhuo",
        "SVNR",
        "https://randomuser.me/api/portraits/men/96.jpg",
        "https://randomuser.me/api/portraits/med/men/96.jpg",
        "https://randomuser.me/api/portraits/thumb/men/96.jpg"
    ],
    [
        "female",
        "Julie",
        "Rasmussen",
        "Vestervang",
        "Jystrup",
        "Nordjylland",
        "Denmark",
        "julie.rasmussen@example.com",
        "angryrabbit875",
        "beagle",
        "CPR",
        "https://randomuser.me/api/portraits/women/74.jpg",
        "https://randomuser.me/api/portraits/med/women/74.jpg",
        "https://randomuser.me/api/portraits/thumb/women/74.jpg"
    ],
    [
        "male",
        "Douglas",
        "Morgan",
        "Camden Ave",
        "Palmdale",
        "Missouri",
        "United States",
        "douglas.morgan@example.com",
        "whiteduck989",
        "1210",
        "SSN",
        "https://randomuser.me/api/portraits/men/46.jpg",
        "https://randomuser.me/api/portraits/med/men/46.jpg",
        "https://randomuser.me/api/portraits/thumb/men/46.jpg"
    ],
    [
        "female",
        "Eugenia",
        "Ecker",
        "Goethestraße",
        "Frohburg",
        "Thüringen",
        "Germany",
        "eugenia.ecker@example.com",
        "silverbear552",
        "scorpion",
        "SVNR",
        "https://randomuser.me/api/portraits/women/20.jpg",
        "https://randomuser.me/api/portraits/med/women/20.jpg",
        "https://randomuser.me/api/portraits/thumb/women/20.jpg"
    ],
    [
        "female",
        "Rose",
        "Fortin",
        "Simcoe St",
        "Greenwood",
        "Nunavut",
        "Canada",
        "rose.fortin@example.com",
        "smallzebra115",
        "natural",
        "SIN",
        "https://randomuser.me/api/portraits/women/51.jpg",
        "https://randomuser.me/api/portraits/med/women/51.jpg",
        "https://randomuser.me/api/portraits/thumb/women/51.jpg"
    ],
    [
        "female",
        "Camila",
        "Richards",
        "Miller Ave",
        "Traralgon",
        "Australian Capital Territory",
        "Australia",
        "camila.richards@example.com",
        "angrylion425",
        "riders",
        "TFN",
        "https://randomuser.me/api/portraits/women/91.jpg",
        "https://randomuser.me/api/portraits/med/women/91.jpg",
        "https://randomuser.me/api/portraits/thumb/women/91.jpg"
    ],
    [
        "female",
        "Kübra",
        "Baturalp",
        "Necatibey Cd",
        "Ordu",
        "Bartın",
        "Turkey",
        "kubra.baturalp@example.com",
        "redlion787",
        "gambler",
        "",
        "https://randomuser.me/api/portraits/women/24.jpg",
        "https://randomuser.me/api/portraits/med/women/24.jpg",
        "https://randomuser.me/api/portraits/thumb/women/24.jpg"
    ],
    [
        "male",
        "Jakub",
        "Strandheim",
        "Brugata",
        "Prestegårdshagen",
        "Telemark",
        "Norway",
        "jakub.strandheim@example.com",
        "purpleleopard688",
        "pirate",
        "FN",
        "https://randomuser.me/api/portraits/men/30.jpg",
        "https://randomuser.me/api/portraits/med/men/30.jpg",
        "https://randomuser.me/api/portraits/thumb/men/30.jpg"
    ],
    [
        "female",
        "Taiara",
        "da Cruz",
        "Rua Boa Vista ",
        "Guaratinguetá",
        "Minas Gerais",
        "Brazil",
        "taiara.dacruz@example.com",
        "tinymeercat607",
        "cocacola",
        "CPF",
        "https://randomuser.me/api/portraits/women/87.jpg",
        "https://randomuser.me/api/portraits/med/women/87.jpg",
        "https://randomuser.me/api/portraits/thumb/women/87.jpg"
    ],
    [
        "male",
        "Kevin",
        "Burton",
        "Green Lane",
        "Westminster",
        "Cleveland",
        "United Kingdom",
        "kevin.burton@example.com",
        "goldensnake214",
        "dietcoke",
        "NINO",
        "https://randomuser.me/api/portraits/men/78.jpg",
        "https://randomuser.me/api/portraits/med/men/78.jpg",
        "https://randomuser.me/api/portraits/thumb/men/78.jpg"
    ],
    [
        "female",
        "Maxine",
        "Torres",
        "Taylor St",
        "New Orleans",
        "Minnesota",
        "United States",
        "maxine.torres@example.com",
        "orangeladybug222",
        "steffi",
        "SSN",
        "https://randomuser.me/api/portraits/women/15.jpg",
        "https://randomuser.me/api/portraits/med/women/15.jpg",
        "https://randomuser.me/api/portraits/thumb/women/15.jpg"
    ],
    [
        "male",
        "Elias",
        "Takala",
        "Mannerheimintie",
        "Orimattila",
        "Northern Ostrobothnia",
        "Finland",
        "elias.takala@example.com",
        "yellowbutterfly698",
        "woody",
        "HETU",
        "https://randomuser.me/api/portraits/men/23.jpg",
        "https://randomuser.me/api/portraits/med/men/23.jpg",
        "https://randomuser.me/api/portraits/thumb/men/23.jpg"
    ],
    [
        "male",
        "Aaron",
        "Jones",
        "Montreal Street",
        "Porirua",
        "Southland",
        "New Zealand",
        "aaron.jones@example.com",
        "ticklishtiger486",
        "direct",
        "",
        "https://randomuser.me/api/portraits/men/53.jpg",
        "https://randomuser.me/api/portraits/med/men/53.jpg",
        "https://randomuser.me/api/portraits/thumb/men/53.jpg"
    ],
    [
        "female",
        "Yvonne",
        "Heymann",
        "Kirchstraße",
        "Mayen-Koblenz",
        "Berlin",
        "Germany",
        "yvonne.heymann@example.com",
        "redmouse455",
        "second",
        "SVNR",
        "https://randomuser.me/api/portraits/women/9.jpg",
        "https://randomuser.me/api/portraits/med/women/9.jpg",
        "https://randomuser.me/api/portraits/thumb/women/9.jpg"
    ],
    [
        "male",
        "Niklas",
        "Tolonen",
        "Nordenskiöldinkatu",
        "Utajärvi",
        "North Karelia",
        "Finland",
        "niklas.tolonen@example.com",
        "redfrog893",
        "christine",
        "HETU",
        "https://randomuser.me/api/portraits/men/52.jpg",
        "https://randomuser.me/api/portraits/med/men/52.jpg",
        "https://randomuser.me/api/portraits/thumb/men/52.jpg"
    ],
    [
        "female",
        "María del Carmen",
        "Samaniego",
        "Corredor Sur Arevalo",
        "Santiago Cuautlalpan (Texcoco)",
        "Estado de Mexico",
        "Mexico",
        "mariadelcarmen.samaniego@example.com",
        "beautifulfrog187",
        "kitchen",
        "NSS",
        "https://randomuser.me/api/portraits/women/17.jpg",
        "https://randomuser.me/api/portraits/med/women/17.jpg",
        "https://randomuser.me/api/portraits/thumb/women/17.jpg"
    ],
    [
        "female",
        "Deeksha",
        "Saniel",
        "Mall Rd",
        "Sonipat",
        "Meghalaya",
        "India",
        "deeksha.saniel@example.com",
        "redelephant616",
        "aztnm",
        "UIDAI",
        "https://randomuser.me/api/portraits/women/66.jpg",
        "https://randomuser.me/api/portraits/med/women/66.jpg",
        "https://randomuser.me/api/portraits/thumb/women/66.jpg"
    ],
    [
        "male",
        "Rushil",
        "Sheikh",
        "Dwaraka Nagar",
        "Jabalpur",
        "Rajasthan",
        "India",
        "rushil.sheikh@example.com",
        "blackpanda329",
        "nomore",
        "UIDAI",
        "https://randomuser.me/api/portraits/men/15.jpg",
        "https://randomuser.me/api/portraits/med/men/15.jpg",
        "https://randomuser.me/api/portraits/thumb/men/15.jpg"
    ],
    [
        "female",
        "Begüm",
        "Barbarosoğlu",
        "Fatih Sultan Mehmet Cd",
        "Tunceli",
        "Erzincan",
        "Turkey",
        "begum.barbarosoglu@example.com",
        "tinyduck628",
        "jennaj",
        "",
        "https://randomuser.me/api/portraits/women/93.jpg",
        "https://randomuser.me/api/portraits/med/women/93.jpg",
        "https://randomuser.me/api/portraits/thumb/women/93.jpg"
    ],
    [
        "female",
        "یسنا",
        "مرادی",
        "پارک دانشجو",
        "نجف‌آباد",
        "اصفهان",
        "Iran",
        "ysn.mrdy@example.com",
        "bigswan202",
        "badger",
        "",
        "https://randomuser.me/api/portraits/women/30.jpg",
        "https://randomuser.me/api/portraits/med/women/30.jpg",
        "https://randomuser.me/api/portraits/thumb/women/30.jpg"
    ],
    [
        "female",
        "Vanda",
        "Harhalis",
        "V'yacheslava Lipinskogo",
        "Pervomaysk",
        "Zakarpatska",
        "Ukraine",
        "vanda.harhalis@example.com",
        "bigelephant200",
        "streaming",
        "",
        "https://randomuser.me/api/portraits/women/11.jpg",
        "https://randomuser.me/api/portraits/med/women/11.jpg",
        "https://randomuser.me/api/portraits/thumb/women/11.jpg"
    ],
    [
        "male",
        "شایان",
        "رضایی",
        "پیروزی",
        "پاکدشت",
        "گیلان",
        "Iran",
        "shyn.rdyy@example.com",
        "beautifulbird908",
        "armstron",
        "",
        "https://randomuser.me/api/portraits/men/18.jpg",
        "https://randomuser.me/api/portraits/med/men/18.jpg",
        "https://randomuser.me/api/portraits/thumb/men/18.jpg"
    ],
    [
        "female",
        "Jessica",
        "Robinson",
        "Royal Road",
        "Christchurch",
        "Auckland",
        "New Zealand",
        "jessica.robinson@example.com",
        "whitefrog142",
        "shuang",
        "",
        "https://randomuser.me/api/portraits/women/65.jpg",
        "https://randomuser.me/api/portraits/med/women/65.jpg",
        "https://randomuser.me/api/portraits/thumb/women/65.jpg"
    ],
    [
        "female",
        "Carolyn",
        "Davidson",
        "Preston Rd",
        "Torrance",
        "Oklahoma",
        "United States",
        "carolyn.davidson@example.com",
        "redpeacock170",
        "11111111",
        "SSN",
        "https://randomuser.me/api/portraits/women/19.jpg",
        "https://randomuser.me/api/portraits/med/women/19.jpg",
        "https://randomuser.me/api/portraits/thumb/women/19.jpg"
    ],
    [
        "female",
        "Tara",
        "Dean",
        "Daisy Dr",
        "Port Macquarie",
        "Tasmania",
        "Australia",
        "tara.dean@example.com",
        "purpleswan835",
        "driver",
        "TFN",
        "https://randomuser.me/api/portraits/women/87.jpg",
        "https://randomuser.me/api/portraits/med/women/87.jpg",
        "https://randomuser.me/api/portraits/thumb/women/87.jpg"
    ]
]







  document.body.style.padding="0";
  document.body.style.margin="0";
  document.body.style.boxSizing="border-box";
  document.body.style.backgroundColor="AliceBlue";
  
  let parent=document.createElement("div");
  document.body.appendChild(parent);
  parent.classList.add("top");
  parent.style.display="flex";
  parent.style.justifyContent="space-between";
  parent.style.backgroundColor="red";
  parent.style.padding="20px";
  
  let inven=document.createElement("div");
  document.body.appendChild(inven);
  inven.style.display="flex";
  inven.style.flexWrap="wrap";
  inven.style.justifyContent="center";

  for(let i=0; i<arr.length; i++){
    inven.innerHTML+=`
    <div 
    style="background-color: white; border-radius: 10px; border: 2px solid white; margin: 10px; padding: 6px; width: 275px; box-shadow: 5px 5px 10px 2px rgba(0,0,0,0.5);"
    >
        <img src="${arr[i][11]}" style="border-radius: 10px;"><br>
        <p1 style="color: #008080;">${arr[i][1]} ${arr[i][2]}</p1><br>
        <p1 style="color: #000080;">${arr[i][0]}</p1><br>
        <p1 style="color: #FF0000;">${arr[i][6]}</p1><br>
        <p1 style="color: #008000;">${arr[i][5]}</p1><br>
        <p1 style="color: #0000FF;">${arr[i][7]}</p1><br>
        <p1 style="color: #800080;">${arr[i][8]}</p1><br>
    </div>`;
}